version: '3.1'

services:
  cumulonimbus_db:
    container_name: cumulonimbus_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASENAME}
    ports:
      - "5432:5432"
    volumes:
      - cumulonimbus_data:/var/lib/postgresql/

  cumulonimbus_app:
    container_name: cumulonimbus_app
    build: .
    image: cumulonimbus:1.0
    ports:
      - "8080:8080"
    depends_on:
      - cumulonimbus_db
    env_file:
      - .env
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - ./cpn135-parcial-2-5b4b913651e3.json:/app/credentials.json

volumes:
  cumulonimbus_data:
